version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: DockerFile.dev
            context: .
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres_password
            - PGPORT=5432